# -*- coding: utf-8 -*-
"""Proyek Akhir Klasifikasi Gambar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/irfanmaha/proyek-akhir-klasifikasi-gambar.c7cbbdb5-95a7-4a29-b33e-3babdf93ca58.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260419/auto/storage/goog4_request%26X-Goog-Date%3D20260419T190400Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Dc122adf498ac3c97afb302989350451c810f7414c42b6b1adcd8eb5acff4da1db52cb46861ffa32799cd96629f401b01509debb199c04a110e8a369eaf73792c770f420bd66aa53e450381f99460956b51fbf6966d75a4582cf7cc9fa985ddaa07b05f37bb3cc67ada6d2ca69f53cc6033187c5298983acbe6db4033fdd79d7f487a1c71f352a38335e24e481289704232ea3d47af11e7f42a81bc592a1e833518d563d95fac4ef036713df48015f42d807a7db7fe7bcf0dbbf1bccc79a8a2d599f840fb6d64c1576eb21bb09ec6556304b3a86b73c42af2f96bcabb259cf6d6ff3860ded46e14ba4f88ae3dd9916eed9a163ad0783c8cb6cf2ca82f2efc4b52
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
alessiocorrado99_animals10_path = kagglehub.dataset_download('alessiocorrado99/animals10')

print('Data source import complete.')

"""# Proyek Klasifikasi Gambar: [Animals]
- **Nama:** Irfan Maulana Hakim
- **Email:** irfanmaulanahakim04@gmail.com
- **ID Dicoding:** irfan1704

## Import Semua Packages/Library yang Digunakan
"""

# install library tambahan

!pip install tensorflowjs -q

import os
import random
import zipfile
import shutil
import warnings
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns
warnings.filterwarnings('ignore')

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import (
    EarlyStopping, ModelCheckpoint, ReduceLROnPlateau)

from sklearn.metrics import classification_report, confusion_matrix

print('semua libary berhasil di import')
print(f' TensorFlow version: {tf.__version__}')
print(f'  GPU Available    : {tf.config.list_physical_devices("GPU")}')

"""## Data Preparation

### Data Loading
"""

# lokasi dataset di Kaggle
base_path = '/kaggle/input/datasets/alessiocorrado99/animals10/raw-img'

# cek isi folder
class_dirs = sorted([
    d for d in os.listdir(base_path)
    if os.path.isdir(os.path.join(base_path, d))])
print(f'Jumlah kelas : {len(class_dirs)}')
print(f'Kelas : {class_dirs}')

# menampilkan 1 gambar dari setiap kelas

fig, axes = plt.subplots(2, 5, figsize=(18, 7)) # membuat grid plot 2 x 5
fig.suptitle('contoh gambar perkelas dan resolusi tidak seragam',
             fontsize=13, fontweight='bold')

for idx, class_name in enumerate(class_dirs): # iterasi setiap kelas beserta index nya
  class_path = os.path.join(base_path, class_name)
  sample_img = os.listdir(class_path)[0]
  img_path = os.path.join(class_path, sample_img)
  img = mpimg.imread(img_path)

  ax = axes[idx // 5][idx % 5] # menentukan posisi subplot berdasarkan index
  ax.imshow(img)
  ax.set_title(f'{class_name}\n{img.shape[0]}x{img.shape[1]}', fontsize=10)
  ax.axis('off')

plt.tight_layout()
plt.show()
print('resolusi tiap gambar berbeda-beda')

"""### Data Preprocessing"""

import shutil

# copy dataset ke working directory dari read-only
# mendefinisikan path sumber dataset dari kaggle
src_path = '/kaggle/input/datasets/alessiocorrado99/animals10/raw-img'
base_path = '/kaggle/working/raw-img'

if not os.path.exists(base_path):
    shutil.copytree(src_path, base_path)
    print('dataset berhasil dicopy')
else:
    print('dataset tersedia')

#rename nama kelas dari Italia ke Inggris
translate = {
    'cane'       : 'dog',
    'cavallo'    : 'horse',
    'elefante'   : 'elephant',
    'farfalla'   : 'butterfly',
    'gallina'    : 'chicken',
    'gatto'      : 'cat',
    'mucca'      : 'cow',
    'pecora'     : 'sheep',
    'ragno'      : 'spider',
    'scoiattolo' : 'squirrel'}

for italian, english in translate.items(): # iterasi setiap nama kelas
    src = os.path.join(base_path, italian)
    dst = os.path.join(base_path, english)
    if os.path.exists(src):
        os.rename(src, dst)

CLASS_NAMES = sorted([ # mengambil daftar nama kelas yang sudah di rename
    d for d in os.listdir(base_path)
    if os.path.isdir(os.path.join(base_path, d))])

print(f'CLASS_NAMES : {CLASS_NAMES}')

# konfig
IMG_SIZE = (224, 224) # ukuran gambar 224 piksel
BATCH_SIZE = 32 # jumlah gambar yg di proses dalam satu iterasi training
RANDOM_SEED = 42 # memastikan hasil random yang konsisten

# augmentasi untuk data training
train_datagen = ImageDataGenerator(
    rescale = 1./255,
    rotation_range = 30,
    width_shift_range = 0.2,
    height_shift_range = 0.2,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True,
    fill_mode = 'nearest')

# validation dan test untuk rescale
val_test_datagen = ImageDataGenerator(rescale = 1./255)

print(f'IMG_SIZE  : {IMG_SIZE}')
print(f'BATCH_SIZE: {BATCH_SIZE}')

"""#### Split Dataset"""

import shutil, os

# Hapus folder lama jika sudah ada
if os.path.exists('dataset_split'):
    shutil.rmtree('dataset_split')

# membuat folder baru train, val, dan test
DATASET_DIR = 'dataset_split'
for split in ['train', 'validation', 'test']:
    for class_name in CLASS_NAMES:
        os.makedirs(os.path.join(DATASET_DIR, split, class_name), exist_ok=True)

# copy dan split gambar
split_counts = {'train': 0, 'validation': 0, 'test': 0}

for class_name in CLASS_NAMES:
    class_path = os.path.join('/kaggle/working/raw-img', class_name)
    all_images = [
        f for f in os.listdir(class_path)
        if os.path.isfile(os.path.join(class_path, f))]

    random.seed(42)
    random.shuffle(all_images)

    n = len(all_images)
    n_train = int(n * 0.70)
    n_val = int(n * 0.15)

    train_imgs = all_images[:n_train]
    val_imgs   = all_images[n_train:n_train + n_val]
    test_imgs  = all_images[n_train + n_val:]

    for img in train_imgs: # copy gambar train ke folder train
        shutil.copy(os.path.join(class_path, img),
                    os.path.join(DATASET_DIR, 'train', class_name, img))
    for img in val_imgs: # copy gambar validation ke folder validation
        shutil.copy(os.path.join(class_path, img),
                    os.path.join(DATASET_DIR, 'validation', class_name, img))
    for img in test_imgs: # copy gambar test ke folder test
        shutil.copy(os.path.join(class_path, img),
                    os.path.join(DATASET_DIR, 'test', class_name, img))

# menambahkan jumlah gambar ke counter masing-masing split
    split_counts['train']      += len(train_imgs)
    split_counts['validation'] += len(val_imgs)
    split_counts['test']       += len(test_imgs)

print(f'train : {split_counts["train"]} gambar')
print(f'validation : {split_counts["validation"]} gambar')
print(f'test  : {split_counts["test"]} gambar')
print(f'total : {sum(split_counts.values())} gambar')

"""## Modelling"""

# membuat generator untuk train, val dan test

# generator untuk data training dengan augmentasi
train_generator = train_datagen.flow_from_directory(
    os.path.join(DATASET_DIR, 'train'),
    target_size = IMG_SIZE,
    batch_size = BATCH_SIZE,
    class_mode = 'categorical', # label dalam bentuk one hot encoding
    shuffle = True)

# generator untuk data validation tanpa augmentasi
val_generator = val_test_datagen.flow_from_directory(
    os.path.join(DATASET_DIR, 'validation'),
    target_size = IMG_SIZE,
    batch_size = BATCH_SIZE,
    class_mode = 'categorical', # label dalam bentuk one hot encoding
    shuffle = False)

# generator untuk data test tanpa augmentasi
test_generator = val_test_datagen.flow_from_directory(
    os.path.join(DATASET_DIR, 'test'),
    target_size = IMG_SIZE,
    batch_size = BATCH_SIZE,
    class_mode = 'categorical', # label dalam bentuk one hot encoding
    shuffle = False)

# membuat model sequential, conv2d dan pooling layer
model = keras.Sequential([
    keras.layers.Input(shape=(*IMG_SIZE, 3)),

    # layer ke 1
    layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D(2, 2),
    layers.Dropout(0.25), # menonaktif neuron 25% untuk mencegah overfitting

    # layer ke 2
    layers.Conv2D(128, (3,3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D(2, 2),
    layers.Dropout(0.25), # menonaktif neuron 25% untuk mencegah overfitting

    # layer ke 3
    layers.Conv2D(256, (3,3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D(2, 2),
    layers.Dropout(0.25), # menonaktif neuron 25% untuk mencegah overfitting

    # layer ke 4
    layers.Conv2D(512, (3,3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D(2, 2),
    layers.Dropout(0.25), # menonaktif neuron 25% untuk mencegah overfitting

    # klasifikasi
    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')],
    name='Animals10_CNN')

# kompilasi model dengan optimizer
model.compile(
    optimizer = keras.optimizers.Adam(learning_rate=1e-3),
    loss  = 'categorical_crossentropy',
    metrics = ['accuracy']) # metriks yang dipantau selama training

# custom callback - berhenti saat akurasi mencapai >= 85%
class MyCallback(keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        if (logs.get('accuracy') >= 0.95 and
            logs.get('val_accuracy') >= 0.95):
            print('\nTarget 95% tercapai')
            self.model.stop_training = True # menghentikan proses training lebih awal

callbacks = [ # menyimpan model terbaik selama training berdasarkan val accuracy
    ModelCheckpoint(
        filepath = 'best_model.keras',
        monitor = 'val_accuracy',
        save_best_only = True,
        verbose = 1),

    EarlyStopping(
        monitor = 'val_accuracy',
        patience = 15, # jumlah epochs toleransi jika tidak ada perubahan
        restore_best_weights = True,
        verbose = 1),

    ReduceLROnPlateau(
        monitor = 'val_loss',
        factor = 0.5,
        patience = 5,
        min_lr = 1e-6, # batas minimum learning rate agar tidak terlalu kecil
        verbose = 1),

    MyCallback()
]

print('Callback siap digunakan')

# training model
history = model.fit(
    train_generator,
    epochs = 100,
    validation_data = val_generator,
    callbacks = callbacks,
    verbose = 1)

"""## Evaluasi dan Visualisasi"""

test_loss, test_acc = model.evaluate(test_generator) # evaluasi peforma model dengan data testing
print(f'Test Accuracy: {test_acc:.2f}') # menampilkan hasil tset akurasi dengan format 2 angka desimal

# plot akurasi dan loss
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('hasil training model', fontsize=13, fontweight='bold')

epochs_range = range(1, len(history.history['accuracy']) + 1)

# plot akurasi
axes[0].plot(epochs_range,
             history.history['accuracy'],
             'b-o',
             label='train accuracy')

# plot val akurasi
axes[0].plot(epochs_range,
             history.history['val_accuracy'],
             'r-o',
             label='val accuracy')

# garis target akurasi 85%
axes[0].axhline(y=0.85,
               color='yellow',
               linestyle='--',
               label='target 85%')
axes[0].set_title('akurasi model')
axes[0].set_xlabel('epochs')
axes[0].set_ylabel('accuracy')
axes[0].legend()
axes[0].grid(True)

# plot loss
axes[1].plot(epochs_range,
            history.history['loss'],
             'b-o',
             label='train loss')
axes[1].plot(epochs_range,
            history.history['val_loss'],
            'r-o',
            label='val loss')
axes[1].set_title('loss model')
axes[1].set_xlabel('epoch')
axes[1].set_ylabel('loss')
axes[1].legend()
axes[1].grid(True)

plt.tight_layout()
plt.show()

# confusion matrix
test_generator.reset() # reset generator, prediksi dimulai dari awal data test
y_pred = np.argmax(model.predict(test_generator), axis=1)
y_true = test_generator.classes

cm = confusion_matrix(y_true, y_pred) # membuat confusion matrix dari label asli dan prediksi sebelumnya

# membuat figure untuk menampilkan heatmap confusion matrix
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
           xticklabels=CLASS_NAMES,
           yticklabels=CLASS_NAMES)
plt.title('Confusion matrix', fontsize=13, fontweight='bold')
plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.tight_layout()
plt.show()

print(classification_report(y_true, y_pred, target_names=CLASS_NAMES))

"""## Konversi Model"""

# konversi model savedmodel
import tensorflowjs as tfjs

saved_model_path = '/kaggle/working/saved_model'
model.export(saved_model_path)
print(f'savedmodel berhasil disimpan di: {saved_model_path}')

# konversi model tf-lite
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)
tflite_model = converter.convert()

tflite_path = '/kaggle/working/model.tflite'
with open(tflite_path, 'wb') as f:
    f.write(tflite_model)

print(f'tf-lite berhasil disimpan di: {tflite_path}')
print(f'ukuran file: {os.path.getsize(tflite_path) / 1024 / 1024:.2f} MB')

# konversi model tfjs
tfjs_path = '/kaggle/working/tfjs_model'
tfjs.converters.convert_tf_saved_model(saved_model_path, tfjs_path)
print(f'tfjs berhasil disimpan di: {tfjs_path}')

"""## Inference (Optional)"""

# inferensi savedmodel

# load savedmodel yang sudah disimpan
loaded_model = tf.saved_model.load(saved_model_path)

# ambil fungsi inferensi dari savedmodel
infer = loaded_model.signatures['serving_default']

# ambil 1 gambar random dari test set
test_class = random.choice(CLASS_NAMES) # kelas random
test_class_path = os.path.join(DATASET_DIR, 'test', test_class)
test_img_name = random.choice(os.listdir(test_class_path)) # gambar random
test_img_path = os.path.join(test_class_path, test_img_name)

# load dan preprocessing gambar
img = tf.keras.utils.load_img(test_img_path, target_size=IMG_SIZE) # load gambar dan resize ke 224 x 224
img_array = tf.keras.utils.img_to_array(img) # ubah gambar menjadi array numpy
img_array = img_array / 255.0
img_array = tf.expand_dims(img_array,axis=0) # menambahkan dimensi batch menjadi(1, 224, 224, 3)
img_tensor = tf.cast(img_array, tf.float32) # mengubah tipe float32 sesuai input model

# inferensi
output = infer(img_tensor) # masukan gambar ke model
output_key = list(output.keys())[0]
predictions = output[output_key].numpy() # ambil hasil prediksi ke bentu numpy

# hasil prediksi
predicted_index = np.argmax(predictions[0]) # index kelas dengan probabilitas tinggi
predicted_class = CLASS_NAMES[predicted_index] # nama kelas hasil prediksi
confidence = predictions[0][predicted_index] * 100 # keyakinan model dalam persen

# tampilkan gambar dan hasil prediksi
plt.figure(figsize=(5, 5))
plt.imshow(img)
plt.axis('off') # sembunyikan axis
plt.title(
    f'true label : {test_class}\n'
    f'predicted : {predicted_class}\n'
    f'confidence : {confidence:.2f}%',
    fontsize=13)

plt.tight_layout()
plt.show()

print(f'true label : {test_class}')
print(f'predicted : {predicted_class}')
print(f'confidence : {confidence:.2f}%')
print(f'hasil :{"benar" if predicted_class == test_class else "salah"}')